# Generated by Django 5.1.6 on 2025-03-11 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yearFounded', models.IntegerField()),
                ('outsideEurope', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Baloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('S', 'Small Baloon'), ('M', 'Medium Baloon'), ('L', 'Large Baloon')], max_length=1)),
                ('manufacturer', models.CharField(max_length=100)),
                ('maxPassengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('yearBirth', models.IntegerField()),
                ('totalFlightHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.CharField(choices=[('J', 'Junior'), ('I', 'Intermediate'), ('S', 'Senior')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('takeOffAirport', models.CharField(max_length=100)),
                ('landAirport', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_photos/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airline')),
                ('baloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.baloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='AirlinePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pilot')),
            ],
        ),
    ]
